# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DebianDay São Paulo 2018
email: kanashiro@debian.org
description: > # this means to ignore newlines until "baseurl:"
  No DebianDay São Paulo 2018 iremos comemorar o aniversário de 25 anos do
  projeto Debian.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
